#################################################################################
### conda added to PATH. Use 'source activate' rather than 'conda activate'   ###
### Do not run 'conda init' if prompted unless you have read and understood:  ###
###   /p/system/packages/anaconda/2020.07/bin/conda init --help               ###
### and                                                                       ###
###   https://docs.anaconda.com/anaconda/user-guide/faq/#installing-anaconda  ###
#################################################################################
Traceback (most recent call last):
  File "post-processing/avantgarde_post.py", line 18, in <module>
    data = pd.read_csv(fname, usecols=columns)
  File "/p/system/packages/anaconda/2020.07/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/p/system/packages/anaconda/2020.07/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/p/system/packages/anaconda/2020.07/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/p/system/packages/anaconda/2020.07/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/p/system/packages/anaconda/2020.07/lib/python3.8/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/p/system/packages/anaconda/2020.07/lib/python3.8/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/p/system/packages/anaconda/2020.07/lib/python3.8/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/avantgarde/avantgarde_ensemble_2022-03-28T13:09:29.107.csv'
